### ISSUE TITLE
HBD Horoscope command not working

### ISSUE THREAD

**Issue by Angels4everCoding** [clxrityy/mjanglin.com#31]
Hi! I just started using the bot tonight, sent it all up except admin parts cause in the other server I am adding it to the owner hasn't added admin perms yet. 

I tried to use horoscope command but it's giving and error code(linked below) I wasn't sure if it had to do with the cooldown because I used it in a different server about 10-20 minutes before.

![Screenshot_20240913_215952_Discord](https://github.com/user-attachments/assets/2c7b8ba7-2781-4527-82c0-fbe6394809a6)

**Comment by clxrityy** [comment]
I hopefully patched with [this commit](https://github.com/clxrityy/mjanglin.com/commit/b6407500b972d0336bf4647d5a2e77a2b1cc473b).

Cooldowns were storing the same **userId**'s while different guilds, likely what was causing the error. Cooldowns are now global and have no reliance to guilds.

Thanks
